'use strict';

const fs = require('fs');
const path = require('path');
const { parseNextProgram, parseNextSource } = require('../src/grammar');
const { generateAutoBonds, claimSimilarity } = require('../src/runtime/next/auto-bond');
const { buildMyceliumGraph, buildNextFieldGraph, formatMermaidGraph } = require('../src/runtime/next/mycelium-graph');
const { buildHotReloadPatch, applyHotReload, readSourceWithEvolved } = require('../src/runtime/next/hot-reload');
const { runFieldEngine } = require('../src/runtime/next/field-engine');
const { executeProgram } = require('../src/vm/unified-executor');
const { publishCells } = require('../src/runtime/next/mycelium-store');

let passed = 0;
let failed = 0;

function assert(cond, msg) {
  if (cond) { passed++; console.log(`  \x1b[32mPASS\x1b[0m ${msg}`); }
  else { failed++; console.log(`  \x1b[31mFAIL\x1b[0m ${msg}`); }
}

console.log('\n\x1b[36m═══ Next Profile v0.4 — AutoBond + Mycelium Graph + Hot Reload ═══\x1b[0m\n');

const myceliumDir = path.join(__dirname, '../artifacts/mycelium-test-v04');
const evolvedDir = path.join(__dirname, '../artifacts/evolved-test-v04');
const genesisPath = path.join(__dirname, '../examples/genesis.next');

for (const dir of [myceliumDir, evolvedDir]) {
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir)) fs.unlinkSync(path.join(dir, f));
  } else {
    fs.mkdirSync(dir, { recursive: true });
  }
}

const src = fs.readFileSync(genesisPath, 'utf8');
const prog = parseNextProgram(src);
assert(prog.autobond?.threshold === 0.38, 'parses AUTOBOND block');

const sim = claimSimilarity('Markets entering risk-off regime', 'Soft landing narrative gaining traction');
assert(sim >= 0, 'claim similarity is computable');

const auto = generateAutoBonds(prog.cells, prog.autobond);
assert(auto.length >= 1, 'AUTOBOND generates bonds between hot cells');

const ast = parseNextSource(src);
const field = runFieldEngine(ast.next, { signals: ['risk-off'], force_flux: true });
assert((field.bonds?.autoGenerated || []).length >= 1, 'field engine applies auto bonds');
assert((field.bonds?.all || []).length >= prog.bonds.length, 'merges explicit + auto bonds');

publishCells('dream_cluster', 'seed', [
  { name: 'peer_cell', claim: 'Peer signal', energy: 0.66, tags: ['public'] }
], { dir: myceliumDir });

const fieldWithMycelium = runFieldEngine(ast.next, {
  signals: ['risk-off'],
  mycelium: {
    absorbed: [{ name: 'seed__peer_cell', claim: 'Peer', energy: 0.6, provenance: 'seed', tags: ['public'] }],
    rejected: []
  }
});
const nextGraph = buildNextFieldGraph(ast, fieldWithMycelium);
const myceliumGraph = buildMyceliumGraph({ dir: myceliumDir, field: fieldWithMycelium });
const mermaid = formatMermaidGraph(nextGraph);
assert(nextGraph.nodes.length >= 3, 'next field graph has cell nodes');
assert(myceliumGraph.nodes.length >= 2, 'mycelium graph has cluster/cell nodes');
assert(mermaid.includes('flowchart TD'), 'mermaid graph renders');

const patch = buildHotReloadPatch({
  fluxCrystals: [{ flux: 'syntax', macro: { body: 'CELL hot_test { energy: 0.9 claim: "test" }' } }],
  autoBonds: field.bonds.autoGenerated.slice(0, 1)
});
assert(patch.includes('CELL hot_test'), 'hot reload patch includes crystallized cell');

const reloaded = applyHotReload(genesisPath, patch, { evolved_dir: evolvedDir });
assert(reloaded.applied === true, 'hot reload writes evolved source');

const evolved = readSourceWithEvolved(genesisPath, { evolved_dir: evolvedDir });
assert(evolved.evolved === true, 'readSourceWithEvolved prefers evolved file');
assert(evolved.source.includes('hot_test'), 'evolved source contains hot patch');

(async () => {
  const run = await executeProgram(ast, {
    quiet: true,
    with_protocol: 'off',
    filename: genesisPath,
    source_path: genesisPath,
    signals: ['risk-off'],
    friction: { 'observe reason decide': 0.85 },
    force_flux: true,
    hot_reload: true,
    evolved_dir: evolvedDir,
    mycelium_dir: myceliumDir,
    publish_mycelium: true
  });

  assert(run.success === true, 'genesis v0.4 runs end-to-end');
  assert(run.next?.hotReload?.applied === true, 'hot reload applied during run');
  assert((run.next?.bonds?.autoGenerated || []).length >= 1, 'run exposes auto-generated bonds');

  console.log(`\n${failed === 0 ? '\x1b[32m' : '\x1b[31m'}${passed} passed, ${failed} failed\x1b[0m\n`);
  process.exit(failed > 0 ? 1 : 0);
})();
