'use strict';

const fs = require('fs');
const path = require('path');
const { parseNextProgram, parseNextSource } = require('../src/grammar');
const { mergeEvolvedThreeWay, formatThreeWayReport } = require('../src/runtime/next/evolved-three-way');
const { runHybridDreams, selectHybridSubgraph } = require('../src/runtime/next/hybrid-dream');
const { publishEvent, readEvents } = require('../src/runtime/next/mycelium-bus');
const { publishCells } = require('../src/runtime/next/mycelium-store');
const { runFieldEngine } = require('../src/runtime/next/field-engine');
const { applyHotReload, evolvedPath } = require('../src/runtime/next/hot-reload');
const { executeProgram } = require('../src/vm/unified-executor');

let passed = 0;
let failed = 0;

function assert(cond, msg) {
  if (cond) { passed++; console.log(`  \x1b[32mPASS\x1b[0m ${msg}`); }
  else { failed++; console.log(`  \x1b[31mFAIL\x1b[0m ${msg}`); }
}

console.log('\n\x1b[36m═══ Next Profile v0.6 — Three-Way Merge + Hybrid Dream + Mycelium Bus ═══\x1b[0m\n');

const myceliumDir = path.join(__dirname, '../artifacts/mycelium-test-v06');
const evolvedDir = path.join(__dirname, '../artifacts/evolved-test-v06');
const genesisPath = path.join(__dirname, '../examples/genesis.next');

for (const dir of [myceliumDir, evolvedDir]) {
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir)) {
      fs.rmSync(path.join(dir, f), { recursive: true, force: true });
    }
  } else {
    fs.mkdirSync(dir, { recursive: true });
  }
}

const src = fs.readFileSync(genesisPath, 'utf8');
const prog = parseNextProgram(src);
assert(prog.dreams.some((d) => d.on === 'hybrid'), 'parses DREAM on hybrid');

const base = 'CELL alpha { claim: "A" energy: 0.5 }\nCELL beta { claim: "B" energy: 0.6 }';
const ours = `${base}\n\n# --- noeon hot-reload ---\nCELL gamma { claim: "C" energy: 0.7 }`;
const theirs = `${base}\n\n# --- noeon hot-reload ---\nCELL delta { claim: "D" energy: 0.8 }`;
const threeWay = mergeEvolvedThreeWay(base, ours, theirs, 'union');
assert(threeWay.addedCells >= 2, 'three-way merge combines ours and theirs additions');
assert(threeWay.conflicts.length === 0, 'three-way merge clean when no overlap');
assert(formatThreeWayReport(threeWay).includes('Three-way'), 'three-way report formats');

const conflictOurs = `${base}\n\n# --- noeon hot-reload ---\nCELL alpha { claim: "A2" energy: 0.9 }`;
const conflictTheirs = `${base}\n\n# --- noeon hot-reload ---\nCELL alpha { claim: "A3" energy: 0.4 }`;
const conflictMerge = mergeEvolvedThreeWay(base, conflictOurs, conflictTheirs, 'union');
assert(conflictMerge.conflicts.length === 1, 'three-way detects dual edits to same cell');
assert(conflictMerge.hasConflictMarkers === true, 'three-way writes conflict markers');

const ast = parseNextSource(src);
const field = runFieldEngine(ast.next, { signals: ['risk-off'], force_flux: true });
assert((field.hybridDreams || []).length >= 1, 'field engine runs hybrid dreams when hybrids exist');
assert((field.spawns?.autoGenerated || []).length >= 1, 'hybrids present for dream subgraph');

const subgraph = selectHybridSubgraph(field.cells);
assert(subgraph.hybrids.length >= 1, 'selectHybridSubgraph finds hybrid cells');
assert(subgraph.subgraph.length >= 2, 'subgraph includes parents');

const manualHybrids = [
  { name: 'h1', energy: 0.7, tags: ['hybrid'], parents: ['a', 'b'], claim: 'H' },
  { name: 'a', energy: 0.5, claim: 'A' },
  { name: 'b', energy: 0.6, claim: 'B' }
];
const dreams = runHybridDreams(manualHybrids, [{ name: 'test', on: 'hybrid', branches: 3, depth: 2 }]);
assert(dreams[0]?.kind === 'hybrid', 'runHybridDreams tags kind hybrid');
assert(dreams[0]?.dominant?.cells?.length >= 2, 'hybrid dream branch has subgraph cells');

publishEvent('dream_cluster', { type: 'test.event', note: 'v06' }, { dir: myceliumDir });
publishCells('dream_cluster', 'v06', [{ name: 'bus_cell', claim: 'Bus', energy: 0.55 }], { dir: myceliumDir });
const events = readEvents('dream_cluster', { dir: myceliumDir });
assert(events.some((e) => e.type === 'test.event'), 'mycelium bus stores custom events');
assert(events.some((e) => e.type === 'cells.published'), 'publishCells emits bus event');

applyHotReload(genesisPath, 'CELL v06_marker { energy: 0.5 claim: "v06" }', { evolved_dir: evolvedDir });
const evo = evolvedPath(genesisPath, { evolved_dir: evolvedDir });
const theirsFile = `${evo}.merged`;
fs.writeFileSync(theirsFile, fs.readFileSync(evo, 'utf8') + '\nCELL v06_theirs { energy: 0.4 claim: "theirs" }\n', 'utf8');
const merged3 = mergeEvolvedThreeWay(src, fs.readFileSync(evo, 'utf8'), fs.readFileSync(theirsFile, 'utf8'));
assert(merged3.merged.includes('v06_theirs') || merged3.addedCells >= 1, 'genesis three-way merge works');

(async () => {
  const run = await executeProgram(ast, {
    quiet: true,
    with_protocol: 'off',
    filename: genesisPath,
    source_path: genesisPath,
    signals: ['risk-off'],
    force_flux: true,
    hot_reload: true,
    evolved_dir: evolvedDir,
    mycelium_dir: myceliumDir,
    publish_mycelium: true
  });

  assert(run.success === true, 'genesis v0.6 runs end-to-end');
  assert((run.next?.hybridDreams || []).length >= 1, 'run exposes hybrid dreams');

  const runEvents = readEvents('dream_cluster', { dir: myceliumDir });
  assert(runEvents.some((e) => e.type === 'field.dominant'), 'run publishes field.dominant event');

  console.log(`\n${failed === 0 ? '\x1b[32m' : '\x1b[31m'}${passed} passed, ${failed} failed\x1b[0m\n`);
  process.exit(failed > 0 ? 1 : 0);
})();
