'use strict';

const fs = require('fs');
const path = require('path');
const { parseNextProgram, parseNextSource } = require('../src/grammar');
const { spawnFromBonds, mergeSpawnCells, hybridName } = require('../src/runtime/next/auto-spawn');
const { diffEvolvedSources, mergeEvolvedSources, formatDiffReport } = require('../src/runtime/next/evolved-sync');
const { buildHotReloadPatch, applyHotReload, evolvedPath } = require('../src/runtime/next/hot-reload');
const { runFieldEngine } = require('../src/runtime/next/field-engine');
const { executeProgram } = require('../src/vm/unified-executor');
const { publishCells } = require('../src/runtime/next/mycelium-store');
const { buildMyceliumGraph, formatMermaidGraph } = require('../src/runtime/next/mycelium-graph');

let passed = 0;
let failed = 0;

function assert(cond, msg) {
  if (cond) { passed++; console.log(`  \x1b[32mPASS\x1b[0m ${msg}`); }
  else { failed++; console.log(`  \x1b[31mFAIL\x1b[0m ${msg}`); }
}

console.log('\n\x1b[36m═══ Next Profile v0.5 — Evolved Sync + Auto Spawn + Mycelium Web ═══\x1b[0m\n');

const myceliumDir = path.join(__dirname, '../artifacts/mycelium-test-v05');
const evolvedDir = path.join(__dirname, '../artifacts/evolved-test-v05');
const genesisPath = path.join(__dirname, '../examples/genesis.next');

for (const dir of [myceliumDir, evolvedDir]) {
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir)) {
      fs.rmSync(path.join(dir, f), { recursive: true, force: true });
    }
  } else {
    fs.mkdirSync(dir, { recursive: true });
  }
}

const src = fs.readFileSync(genesisPath, 'utf8');
const prog = parseNextProgram(src);
assert(prog.autobond?.spawn !== false, 'AUTOBOND spawn defaults to true');

const bonds = [
  { from: 'hypothesis_risk_off', to: 'hypothesis_soft', strength: 0.42, similarity: 0.22, kind: 'resonates', auto: true }
];
const spawns = spawnFromBonds(bonds, prog.cells, prog.autobond);
assert(spawns.length === 1, 'spawnFromBonds creates hybrid cell');
assert(spawns[0].name === hybridName('hypothesis_risk_off', 'hypothesis_soft'), 'hybrid name is canonical');

const merged = mergeSpawnCells(prog.cells, spawns);
assert(merged.length === prog.cells.length + 1, 'mergeSpawnCells adds hybrid without duplicate');

const ast = parseNextSource(src);
const field = runFieldEngine(ast.next, { signals: ['risk-off'], force_flux: true });
assert((field.spawns?.autoGenerated || []).length >= 1, 'field engine auto-spawns from bonds');

const patch = buildHotReloadPatch({
  autoSpawns: field.spawns.autoGenerated.slice(0, 1),
  autoBonds: field.bonds.autoGenerated.slice(0, 1)
});
assert(patch.includes('_hybrid'), 'hot reload patch includes hybrid spawn cell');

applyHotReload(genesisPath, patch, { evolved_dir: evolvedDir });
const evoFile = evolvedPath(genesisPath, { evolved_dir: evolvedDir });
const evolved = fs.readFileSync(evoFile, 'utf8');
const diff = diffEvolvedSources(src, evolved);
assert(diff.added.cells.length >= 1 || diff.hotReloadSections >= 1, 'diff detects evolved additions');
assert(typeof formatDiffReport(diff) === 'string', 'formatDiffReport renders text');

const mergedResult = mergeEvolvedSources(src, evolved, 'union');
assert(mergedResult.merged.includes('_hybrid') || mergedResult.merged.includes('hot-reload'), 'merge produces unified source');

publishCells('dream_cluster', 'genesis', [{ name: 'remote', claim: 'Remote', energy: 0.7 }], { dir: myceliumDir });
const graph = buildMyceliumGraph({ dir: myceliumDir, field });
const mermaid = formatMermaidGraph(graph);
assert(graph.nodes.length >= 2, 'mycelium graph for web API shape');
assert(mermaid.includes('flowchart'), 'mermaid output for web viewer');

const conflictBase = 'CELL foo { claim: "A" energy: 0.5 }';
const conflictEvolved = [
  conflictBase,
  '',
  '# --- noeon hot-reload 2020-01-01T00:00:00.000Z ---',
  'CELL foo { claim: "B" energy: 0.6 }'
].join('\n');
const conflictDiff = diffEvolvedSources(conflictBase, conflictEvolved);
assert(conflictDiff.conflicts.length === 1, 'diff detects cell name conflict');

(async () => {
  const run = await executeProgram(ast, {
    quiet: true,
    with_protocol: 'off',
    filename: genesisPath,
    source_path: genesisPath,
    signals: ['risk-off'],
    force_flux: true,
    hot_reload: true,
    evolved_dir: evolvedDir,
    mycelium_dir: myceliumDir,
    publish_mycelium: true
  });

  assert(run.success === true, 'genesis v0.5 runs end-to-end');
  assert((run.next?.spawns?.autoGenerated || []).length >= 1, 'run exposes auto-spawns');
  assert(run.next?.hotReload?.applied === true, 'hot reload includes spawns');

  console.log(`\n${failed === 0 ? '\x1b[32m' : '\x1b[31m'}${passed} passed, ${failed} failed\x1b[0m\n`);
  process.exit(failed > 0 ? 1 : 0);
})();
