'use strict';

function bridgeNextToCognitive(nextResult, ast) {
  const next = nextResult?.next || nextResult || {};
  const field = next.field || {};
  const narrative = next.narrative || field.narrative || [];
  const dominant = next.dominant || field.dominant;

  const perceive = {
    phase: 'PERCEIVE',
    inputs: (field.cells || []).slice(0, 12).map((c) => ({
      name: c.name,
      energy: c.energy,
      claim: c.claim
    })),
    recall: next.fieldMemory?.recall || field.recall || null
  };

  const reason = {
    phase: 'REASON',
    woven: field.woven || [],
    bonds: (field.bonds?.all || []).length,
    hybrid_dreams: (next.hybridDreams || field.hybridDreams || []).length
  };

  const decide = {
    phase: 'DECIDE',
    dominant: dominant || null,
    narrative: narrative.map((n) => n.text || n),
    semantic: next.fieldMemory?.semantic || null
  };

  const act = {
    phase: 'ACT',
    emissions: field.emissions || [],
    spawns: [
      ...(field.spawns?.executed || next.declaredSpawns || []).map((s) => s.name || s),
      ...(field.spawns?.autoGenerated || []).map((s) => s.name)
    ]
  };

  const reflect = {
    phase: 'REFLECT',
    dream_feedback: next.dreamFeedback || field.dreamFeedback || null,
    evolution: next.evolution?.selected || null,
    lineage_size: next.fieldMemory?.lineage_size || 0
  };

  return {
    profile: 'next→cognitive',
    program: ast?.program || ast?.task || 'next',
    goal: next.goal?.text || ast?.next?.goal?.text || null,
    cycle: [perceive, reason, decide, act, reflect],
    artifact: {
      format: 'noeon-cognitive-bridge-v1',
      summary: dominant
        ? `Dominant cell ${dominant.name} at energy ${dominant.energy}`
        : 'Field cycle completed without dominant',
      narrative_lines: narrative.map((n) => n.text || String(n))
    }
  };
}

module.exports = {
  bridgeNextToCognitive
};
