'use strict';

const { matchPattern } = require('./mycelium-store');

function clamp(v) {
  return Math.max(0, Math.min(1, v));
}

function executeDeclaredSpawns(spawns, cells, field, config = {}) {
  const created = [];
  const names = new Set(cells.map((c) => c.name));

  for (const spawn of spawns || []) {
    if (names.has(spawn.name)) continue;

    let inherited = cells.filter((c) =>
      (spawn.inherit || []).some((p) => matchPattern(c.name, p))
    );

    if (!inherited.length && field?.dominant) {
      inherited = cells.filter((c) => c.name === field.dominant.name);
    }

    if (!inherited.length) continue;

    const avgEnergy = inherited.reduce((s, c) => s + (c.energy ?? 0.5), 0) / inherited.length;
    const energy = clamp(avgEnergy + (config.spawn_energy_bonus ?? 0.08));

    created.push({
      name: spawn.name,
      energy: Number(energy.toFixed(4)),
      claim: spawn.goal || `Spawn thread: ${spawn.name}`,
      tags: ['spawn', 'declared'],
      inherit: inherited.map((c) => c.name),
      lineage: inherited.map((c) => c.name),
      when: [{
        condition: 'energy > 0.52',
        action: 'emit',
        target: `narrative.spawn.${spawn.name}`
      }]
    });
    names.add(spawn.name);
  }

  return created;
}

function recordLineage(memory, field, spawns = []) {
  memory.lineage = memory.lineage || [];
  const entry = {
    at: new Date().toISOString(),
    dominant: field?.dominant?.name || null,
    hybrids: (field?.spawns?.autoGenerated || []).map((s) => s.name),
    declared: spawns.map((s) => s.name),
    auto_spawns: (field?.spawns?.autoGenerated || []).map((s) => ({ name: s.name, parents: s.parents || [] }))
  };
  memory.lineage.push(entry);
  if (memory.lineage.length > 25) memory.lineage = memory.lineage.slice(-25);
  return memory;
}

module.exports = {
  executeDeclaredSpawns,
  recordLineage
};
